seed: 42
epochs: 200
lr: 0.002
weight_decay: 5.0e-05
h: 256
dz: 128
dropout: 0.1
pA: 0.15
pX: 0.2
lambda_rec: 1.0
lambda_rlc: 1.0
lambda_modal: 0.5
margin_init: 0.2
alpha: 0.5
log_every: 20
outdir: outputs/acm
